export const nationalities = [
  { value: "ZW", label: "Zimbabwean" },
  { value: "ZA", label: "South African" },
  { value: "AF", label: "Afghan" },
  { value: "AL", label: "Albanian" },
  { value: "DZ", label: "Algerian" },
  { value: "US", label: "American" },
  { value: "AD", label: "Andorran" },
  { value: "AO", label: "Angolan" },
  { value: "AG", label: "Antiguan and Barbudan" },
  { value: "AR", label: "Argentine" },
  { value: "AM", label: "Armenian" },
  { value: "AU", label: "Australian" },
  { value: "AT", label: "Austrian" },
  { value: "AZ", label: "Azerbaijani" },
  { value: "BS", label: "Bahamian" },
  { value: "BH", label: "Bahraini" },
  { value: "BD", label: "Bangladeshi" },
  { value: "BB", label: "Barbadian" },
  { value: "BY", label: "Belarusian" },
  { value: "BE", label: "Belgian" },
  { value: "BZ", label: "Belizean" },
  { value: "BJ", label: "Beninese" },
  { value: "BT", label: "Bhutanese" },
  { value: "BO", label: "Bolivian" },
  { value: "BA", label: "Bosnian or Herzegovinian" },
  { value: "BW", label: "Motswana" },
  { value: "BR", label: "Brazilian" },
  { value: "GB", label: "British" },
  { value: "BN", label: "Bruneian" },
  { value: "BG", label: "Bulgarian" },
  { value: "BF", label: "Burkinabe" },
  { value: "BI", label: "Burundian" },
  { value: "CV", label: "Cabo Verdean" },
  { value: "KH", label: "Cambodian" },
  { value: "CM", label: "Cameroonian" },
  { value: "CA", label: "Canadian" },
  { value: "CF", label: "Central African" },
  { value: "TD", label: "Chadian" },
  { value: "CL", label: "Chilean" },
  { value: "CN", label: "Chinese" },
  { value: "CO", label: "Colombian" },
  { value: "KM", label: "Comoran" },
  { value: "CG", label: "Congolese" },
  { value: "CR", label: "Costa Rican" },
  { value: "HR", label: "Croatian" },
  { value: "CU", label: "Cuban" },
  { value: "CY", label: "Cypriot" },
  { value: "CZ", label: "Czech" },
  { value: "CD", label: "Congolese" },
  { value: "DK", label: "Danish" },
  { value: "DJ", label: "Djiboutian" },
  { value: "DM", label: "Dominican" },
  { value: "DO", label: "Dominican" },
  { value: "NL", label: "Dutch" },
  { value: "EC", label: "Ecuadorian" },
  { value: "EG", label: "Egyptian" },
  { value: "SV", label: "Salvadoran" },
  { value: "GQ", label: "Equatorial Guinean" },
  { value: "ER", label: "Eritrean" },
  { value: "EE", label: "Estonian" },
  { value: "ET", label: "Ethiopian" },
  { value: "FJ", label: "Fijian" },
  { value: "FI", label: "Finnish" },
  { value: "FR", label: "French" },
  { value: "GA", label: "Gabonese" },
  { value: "GM", label: "Gambian" },
  { value: "GE", label: "Georgian" },
  { value: "DE", label: "German" },
  { value: "GH", label: "Ghanaian" },
  { value: "GR", label: "Greek" },
  { value: "GD", label: "Grenadian" },
  { value: "GT", label: "Guatemalan" },
  { value: "GN", label: "Guinean" },
  { value: "GW", label: "Guinea-Bissauan" },
  { value: "GY", label: "Guyanese" },
  { value: "HT", label: "Haitian" },
  { value: "HN", label: "Honduran" },
  { value: "HU", label: "Hungarian" },
  { value: "IS", label: "Icelander" },
  { value: "IN", label: "Indian" },
  { value: "ID", label: "Indonesian" },
  { value: "IR", label: "Iranian" },
  { value: "IQ", label: "Iraqi" },
  { value: "IE", label: "Irish" },
  { value: "IL", label: "Israeli" },
  { value: "IT", label: "Italian" },
  { value: "CI", label: "Ivorian" },
  { value: "JM", label: "Jamaican" },
  { value: "JP", label: "Japanese" },
  { value: "JO", label: "Jordanian" },
  { value: "KZ", label: "Kazakhstani" },
  { value: "KE", label: "Kenyan" },
  { value: "KI", label: "I-Kiribati" },
  { value: "KW", label: "Kuwaiti" },
  { value: "KG", label: "Kyrgyz" },
  { value: "LA", label: "Laotian" },
  { value: "LV", label: "Latvian" },
  { value: "LB", label: "Lebanese" },
  { value: "LS", label: "Mosotho" },
  { value: "LR", label: "Liberian" },
  { value: "LY", label: "Libyan" },
  { value: "LI", label: "Liechtensteiner" },
  { value: "LT", label: "Lithuanian" },
  { value: "LU", label: "Luxembourger" },
  { value: "MK", label: "Macedonian" },
  { value: "MG", label: "Malagasy" },
  { value: "MW", label: "Malawian" },
  { value: "MY", label: "Malaysian" },
  { value: "MV", label: "Maldivian" },
  { value: "ML", label: "Malian" },
  { value: "MT", label: "Maltese" },
  { value: "MH", label: "Marshallese" },
  { value: "MR", label: "Mauritanian" },
  { value: "MU", label: "Mauritian" },
  { value: "MX", label: "Mexican" },
  { value: "FM", label: "Micronesian" },
  { value: "MD", label: "Moldovan" },
  { value: "MC", label: "Monacan" },
  { value: "MN", label: "Mongolian" },
  { value: "ME", label: "Montenegrin" },
  { value: "MA", label: "Moroccan" },
  { value: "MZ", label: "Mozambican" },
  { value: "MM", label: "Burmese" },
  { value: "NA", label: "Namibian" },
  { value: "NR", label: "Nauruan" },
  { value: "NP", label: "Nepalese" },
  { value: "NZ", label: "New Zealander" },
  { value: "NI", label: "Nicaraguan" },
  { value: "NE", label: "Nigerien" },
  { value: "NG", label: "Nigerian" },
  { value: "KP", label: "North Korean" },
  { value: "NO", label: "Norwegian" },
  { value: "OM", label: "Omani" },
  { value: "PK", label: "Pakistani" },
  { value: "PW", label: "Palauan" },
  { value: "PA", label: "Panamanian" },
  { value: "PG", label: "Papua New Guinean" },
  { value: "PY", label: "Paraguayan" },
  { value: "PE", label: "Peruvian" },
  { value: "PH", label: "Filipino" },
  { value: "PL", label: "Polish" },
  { value: "PT", label: "Portuguese" },
  { value: "QA", label: "Qatari" },
  { value: "RO", label: "Romanian" },
  { value: "RU", label: "Russian" },
  { value: "RW", label: "Rwandan" },
  { value: "KN", label: "Kittian and Nevisian" },
  { value: "LC", label: "Saint Lucian" },
  { value: "VC", label: "Saint Vincentian" },
  { value: "WS", label: "Samoan" },
  { value: "SM", label: "Sammarinese" },
  { value: "ST", label: "Sao Tomean" },
  { value: "SA", label: "Saudi" },
  { value: "SN", label: "Senegalese" },
  { value: "RS", label: "Serbian" },
  { value: "SC", label: "Seychellois" },
  { value: "SL", label: "Sierra Leonean" },
  { value: "SG", label: "Singaporean" },
  { value: "SK", label: "Slovak" },
  { value: "SI", label: "Slovenian" },
  { value: "SB", label: "Solomon Islander" },
  { value: "SO", label: "Somali" },
  { value: "KR", label: "South Korean" },
  { value: "SS", label: "South Sudanese" },
  { value: "ES", label: "Spanish" },
  { value: "LK", label: "Sri Lankan" },
  { value: "SD", label: "Sudanese" },
  { value: "SR", label: "Surinamese" },
  { value: "SZ", label: "Swazi" },
  { value: "SE", label: "Swedish" },
  { value: "CH", label: "Swiss" },
  { value: "SY", label: "Syrian" },
  { value: "TW", label: "Taiwanese" },
  { value: "TJ", label: "Tajik" },
  { value: "TZ", label: "Tanzanian" },
  { value: "TH", label: "Thai" },
  { value: "TL", label: "Timorese" },
  { value: "TG", label: "Togolese" },
  { value: "TO", label: "Tongan" },
  { value: "TT", label: "Trinidadian or Tobagonian" },
  { value: "TN", label: "Tunisian" },
  { value: "TR", label: "Turkish" },
  { value: "TM", label: "Turkmen" },
  { value: "TV", label: "Tuvaluan" },
  { value: "UG", label: "Ugandan" },
  { value: "UA", label: "Ukrainian" },
  { value: "AE", label: "Emirati" },
  { value: "UY", label: "Uruguayan" },
  { value: "UZ", label: "Uzbekistani" },
  { value: "VU", label: "Ni-Vanuatu" },
  { value: "VE", label: "Venezuelan" },
  { value: "VN", label: "Vietnamese" },
  { value: "YE", label: "Yemeni" },
  { value: "ZM", label: "Zambian" }
];
